### ISSUE TITLE
Cloud Run へ Rails アプリケーションの初回デプロイ

### ISSUE THREAD

**Issue by HaruyaFujimoto** [commew/timelogger-api#23]
こちらを実行する。
https://github.com/commew/timelogger-api/pull/22#issuecomment-1487252367
以下引用。

デプロイ先となる Cloud Run のサービスは現在、  コンテナポートを 80 に設定している。  
テストのために nginx イメージをデプロイする関係でそうなった。  
(有効な port を指定しないとデプロイが失敗してテストが進まない)
  
自動デプロイを実際に動かす前に、一度だけ手動で docker イメージのプッシュと Cloud Run のデプロイを行い、  
8080 をコンテナポートに設定する必要がありそう。  
テストのために nginx のイメージにてデプロイする際にも一度手動でデプロイしているので、  
下記のような手順でできることを確認している。

master ブランチに merge するとワークフローが動作するので、その前に一度この手順を行っておくようにする。

```
# サービスアカウントとして gcloud-cli にログイン
gcloud auth login --cred-file="${json-file-path}"

# docker コマンドにて push できるようにするための認証
gcloud auth configure-docker asia-northeast1-docker.pkg.dev \
  --project="${PROJECT_ID}"

# 1度ローカルからイメージを Artifact Registry へ push (このプロジェクトのディレクトリで実行する)
docker build -t ${IMAGE_URL}:init .
docker push ${IMAGE_URL}:init

# Cloud Run デプロイ
gcloud run deploy "${SERVICE_NAME}" \
  --image="${IMAGE_URL}:init" \
  --project="${PROJECT_ID}" \
  --region="${REGION}" \
  --port=8080
```

**Comment by HaruyaFujimoto** [comment]
備考として、Artifact Registry にて以下の料金がかかります。
(参考: https://cloud.google.com/artifact-registry/pricing?hl=ja#storage)

Usage | 料金（GB 単位/月）
-- | --
最大 0.5 GB | 無料
0.5 GB 超 | $0.10

使用する予定の docker イメージをローカルでビルドした際のサイズは 897MB でした。  
ですので1回のデプロイにてだいたい $0.10 弱がコストとしてかかる想定です。

**Comment by HAYASHI-Masayuki** [comment]
> 使用する予定の docker イメージをローカルでビルドした際のサイズは 897MB でした。

ありがとうございます。当初の想定よりはちょっと大きい感じですかね……？
とはいえ1GBは超えなそうという想定の範囲内ではあり、後は実際にRailsアプリケーション載せたときにどうなるか、ですね。どちらにしても個人的には許容範囲内じゃないかなと思います。

**Comment by HaruyaFujimoto** [comment]
時間を見つけて少しスリムにしたい気持ちはあります。。

https://github.com/commew/timelogger-api/issues/23#issuecomment-1488832973
こちら slack にてむちょこさんに連絡しコストについて承知いただけました。
ですので自分の環境にてテストを行った後に、初回デプロイを実行しようと思います。

**Comment by HaruyaFujimoto** [comment]
https://github.com/commew/timelogger-api/issues/23#issue-1646002632
を実行しようとしたがうまく動作しなかったので、サービスを作り直す方法で作業をする予定に変更。  
ローカルからイメージをプッシュして、web のコンソール上で手動でサービスの作成を行う。

**Comment by HAYASHI-Masayuki** [comment]
おつかれさまです！

> [#23 (comment)](https://github.com/commew/timelogger-api/issues/23#issue-1646002632)
> を実行しようとしたがうまく動作しなかったので、サービスを作り直す方法で作業をする予定に変更。

あら、どういう理由でうまく行かなかったのでしょうね。
サービスを作り直すことで動作するとよいのですが。

**Comment by HaruyaFujimoto** [comment]
しばらく手が止まってしまっていたが、このタスクを再開。
試験として自分の GCP アカウントにイメージを push して CloudRun のサービス作成を行った。
当たり前だが、production 環境用の暗号化ファイルを復号されるための鍵がないというエラーがでた。

```
=> Booting Puma
=> Rails 7.0.4.2 application starting in production 
=> Run `bin/rails server --help` for more startup options
Missing encryption key to decrypt file with. Ask your team for your master key and write it to /app/config/credentials/production.key or put it in the ENV['RAILS_MASTER_KEY'].
Exiting
```

初回デプロイを完了させるために GCP の SecretManager の設定と、CloudRun にてシークレット参照の設定をする必要がある。

## ToDo

- [ ] API の git レポジトリにて、.dockerignore を編集し PR を作成する (万が一にローカルでビルドをする際に、鍵ファイルがイメージ内に入らないように)
- [ ] 自分の環境にて、暗号化ファイルと鍵ファイルを新しく生成 (試しのデプロイなので本番データを使わないように)
- [ ] 暗号化ファイル内に必要な設定を記述
- [ ] SecretManager にて新しいシークレットを作成 (鍵ファイルの内容)
- [ ] 暗号化ファイルの内容が変更された状態でコンテナイメージを build
- [ ] build したコンテナにて、鍵ファイルが含まれていないことを確認 (`Missing encryption key to decrypt file with.` のエラーが出ることを確認)
- [ ] コンテナイメージを ArtifactRegistry に push
- [ ] push されたイメージで CloudRun のサービスを新規作成、その際にシークレット参照の設定を行う
  - [ ] 環境変数として公開 `RAILS_MASTER_KEY`

**Comment by HaruyaFujimoto** [comment]
自分の GCP ではテストデプロイを行うことができた。
ただし、echo コントローラは削除済みのため、404 しか確認できなかった。
またウェブ上のコンソール操作にて CloudRun へのデプロイの際にシークレット参照を追加する際に、
バージョンごとに環境変数名を指定する必要がある？様子で、
たまにそこの設定をどうやってもうまくいかないことがあった。
(権限まわりの設定がよくなかったのだろうか、原因不明)

この状態で、ローカルからデプロイ用のサービスアカウントとして CloudRun のデプロイコマンドを実行できるかテストする。

**Comment by HaruyaFujimoto** [comment]
> この状態で、ローカルからデプロイ用のサービスアカウントとして CloudRun のデプロイコマンドを実行できるかテストする。

デプロイ用のサービスアカウントからデプロイが実行できることを確認。
GCP のプロジェクト timelogger-api での初回デプロイへ進む。

echo コントローラが残っている git の commit で初回デプロイすることが確認する上で役に立ちそうだったら、
そのバージョンをデプロイする。

**Comment by HaruyaFujimoto** [comment]
ローカルにて /api/echo のエンドポイントを復活させた。
ローカルにて本番用ビルドを実行し、そのエンドポイントが動くか確認を行い成功。
デプロイへ進む。

GCP のプロジェクト timelogger-api にて、SecretManager を有効にしようとしたところ
画像のようになり有効にできなかった。
こちらに関してはむちょこさんに確認が必要。

<img width="1440" alt="Screenshot 2023-06-08 at 18 36 38" src="https://github.com/commew/timelogger-api/assets/29014709/17d4a29b-ef7c-4b60-b7c5-f8d829832d2f">

この他に、
- ArtifactRegistry へのアクセス権限を私のアカウントへ付与
- SecretManager へのアクセス権限を、私のアカウント、サービスアカウント、CloudRun のサービスに付与する必要がありそう

**Comment by HaruyaFujimoto** [comment]
上記について、無理に SecretManager を使わなくても CloudRun のサービス作成時に環境変数をセットするだけでいいかも？
と思い始めた。
本来は SecretManager を使った方がローテーションとかしやすいのかもしれないが、今回はローテーションが必要になったときに
SecretManager での管理に切り替えでよいのかも。
開発中は RAILS_MASTER_KEY を変更しなきゃいけないということはあまりなさそうなので、
固定の値を環境変数に入れるだけにしようかと思う。

一旦、SecretManager は使わずに進める。

**Comment by HAYASHI-Masayuki** [comment]
いろいろご検討ありがとうございます！
環境変数だと、Secret Managerを使うよりは漏洩が心配ではありますが、Secret Managerを使えるようにするまでの手間を考えると、とりあえず環境変数で進めるのもありかと思います。
引き続きご対応お願いします。
私も今、アカウント登録・取得API回りちょっとずつですが進めています。来週一杯くらいでなんとか完成させたい……。

**Comment by HaruyaFujimoto** [comment]
https://cloud.google.com/run/docs/configuring/environment-variables?hl=ja

こちらに

> 注意: 環境変数をシークレットの保存と利用に使用しないでください。環境変数は、プロジェクト閲覧者以上の権限を持つユーザーに表示されます。代わりに、シークレットの使用ページの説明に沿って、Cloud Run で Secret Manager を使用してください。

とありましたので、稼働させるときには SecretManager を使うようにしたいですね。

むちょこさんに相談するならいくらかかるのかを確認してからだと思い、
SecretManager の料金を確認したところ、
シークレット1つ当たり月に $0.06 くらいかかりそうだったので、
今段階ではとりあえずコストかからない方法でよいかな〜と考えました。

> 環境変数は、プロジェクト閲覧者以上の権限を持つユーザーに表示されます。

との記載から外部に漏れるということが起こるわけではなさそうだし、という考えでした。

私もこれが終わったら機能の方を触っていきたいと思っています！
進行中の林さんの方のタスクもよろしくお願いいたします！🙇
